# Generated by Django 5.2.1 on 2025-05-18 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_season_dislikes_count_season_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='dislikes_count',
        ),
        migrations.RemoveField(
            model_name='season',
            name='likes_count',
        ),
        migrations.CreateModel(
            name='SeasonVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('dislikes_count', models.PositiveIntegerField(default=0)),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='seasons.season')),
            ],
        ),
    ]
