# Generated by Django 5.2.1 on 2025-05-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0004_remove_season_dislikes_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('dislikes_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='SeasonVote',
        ),
    ]
